version: "3"
services:
  db:
    image: mysql:5.7.24
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:5.0.1

  sidekiq:
    build: .
    env_file: .env
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/myapp
    depends_on:
      - db

  web:
    build: .
    env_file: .env
    entrypoint: lib/entrypoint.sh
    volumes:
      - .:/myapp
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
    db_data:
